import Footer from "@/components/shared/Footer";
import { Header } from "@/components/shared/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="sticky top-0 left-0 w-full z-50">
          <Header />
        </div>
        {children}
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
